[info]
url = "http://localhost:3339/"
listen_host = "0.0.0.0"
listen_port = 3338
mnemonic = "test test test test test test test test test test test junk"

[database]
engine = "sqlite"

[ln]
ln_backend = "fakewallet"

[fake_wallet]
supported_units = ["sat"]
fee_percent = 0.0
reserve_fee_min = 0
min_delay_time = 1
max_delay_time = 1

[auth]
auth_enabled = true
openid_discovery = "http://keycloak:8080/realms/cashu/.well-known/openid-configuration"
openid_client_id = "cashu-client"
mint_max_bat = 10
mint = "blind"
get_mint_quote = "clear"
check_mint_quote = "blind"
melt = "none"
get_melt_quote = "none"
check_melt_quote = "none"
swap = "blind"
restore = "blind"
check_proof_state = "none"
